# Generated by Django 3.2.6 on 2023-10-20 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Variable',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('heart_rate', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
    ]
