# Generated by Django 3.2.6 on 2023-10-21 04:06

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('variables', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='variable',
            name='heart_rate',
        ),
        migrations.AddField(
            model_name='variable',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='variable',
            name='name',
            field=models.CharField(default=django.utils.timezone.now, max_length=100, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='variable',
            name='unit',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='variable',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
