# Generated by Django 3.2.6 on 2023-10-20 23:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('variables', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Measurement',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('heart_rate', models.DecimalField(decimal_places=2, max_digits=5)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('variable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='variables.variable')),
            ],
        ),
    ]
