# Generated by Django 3.2.6 on 2023-10-21 04:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('measurements', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='measurement',
            old_name='heart_rate',
            new_name='value',
        ),
    ]
