# Generated by Django 3.2.6 on 2023-10-21 02:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contrato',
            fields=[
                ('id', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('eps', models.CharField(max_length=50)),
                ('descripcion', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('tipo', models.CharField(choices=[('Radiografia', 'radiografia'), ('Tomografia', 'tomografia'), ('Examen de Sangre', 'examen de sangre'), ('Ecografia', 'ecografia'), ('Cita Medica', 'cita medica')], max_length=40)),
                ('descripcion', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('nombre', models.CharField(max_length=100)),
                ('id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('email', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=100)),
                ('tipo_id', models.CharField(choices=[('cedula', 'Cedula'), ('cedula extranjeria', 'Cedula Extranjeria'), ('pasaporte', 'Pasaporte'), ('tarjeta de identidad', 'Tarjeta de Identidad'), ('registro vicil', 'Registro Civil')], max_length=40)),
                ('id_contrato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='facturacion.contrato')),
            ],
        ),
        migrations.CreateModel(
            name='Manual_Tarifario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precio', models.IntegerField()),
                ('id_contrato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='facturacion.contrato')),
                ('id_servicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='facturacion.servicio')),
            ],
        ),
        migrations.CreateModel(
            name='EstadoCuenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='facturacion.paciente')),
                ('id_servicio', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='facturacion.servicio')),
            ],
        ),
    ]
