# Generated by Django 3.2.6 on 2023-10-20 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='estadocuenta',
            old_name='id_paciente',
            new_name='paciente',
        ),
        migrations.RenameField(
            model_name='estadocuenta',
            old_name='id_servicio',
            new_name='servicio',
        ),
    ]
