# Generated by Django 3.2.6 on 2023-10-12 03:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0002_auto_20230930_0943'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contrato',
            fields=[
                ('id', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('eps', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='EstadoCuenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Manual_Tarifario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precio', models.IntegerField()),
                ('id_contrato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='facturacion.contrato', unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('nombre', models.CharField(max_length=100)),
                ('id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('email', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=100)),
                ('tipo_id', models.CharField(choices=[('cedula', 'Cedula'), ('cedula extranjeria', 'Cedula Extranjeria'), ('pasaporte', 'Pasaporte'), ('tarjeta de identidad', 'Tarjeta de Identidad'), ('registro vicil', 'Registro Civil')], max_length=40)),
                ('id_contrato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='facturacion.contrato')),
            ],
        ),
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('tipo', models.CharField(choices=[('Radiografia', 'radiografia'), ('Tomografia', 'tomografia'), ('Examen de Sangre', 'examen de sangre'), ('Ecografia', 'ecografia'), ('Cita Medica', 'cita medica')], max_length=40)),
                ('descripcion', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='Factura',
        ),
        migrations.AddField(
            model_name='manual_tarifario',
            name='id_servicio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='facturacion.servicio', unique=True),
        ),
        migrations.AddField(
            model_name='estadocuenta',
            name='id_paciente',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='facturacion.paciente'),
        ),
        migrations.AddField(
            model_name='estadocuenta',
            name='id_servicio',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='facturacion.servicio'),
        ),
    ]
