# Generated by Django 3.2.6 on 2023-10-20 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0002_EstadoCuenta_migration'),
    ]

    operations = [
        migrations.RenameField(
            model_name='estadocuenta',
            old_name='paciente',
            new_name='id_paciente',
        ),
        migrations.RenameField(
            model_name='estadocuenta',
            old_name='servicio',
            new_name='id_servicio',
        ),
    ]
