# Generated by Django 3.2.6 on 2023-10-12 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0003_auto_20231011_2209'),
    ]

    operations = [
        migrations.AddField(
            model_name='contrato',
            name='descripcion',
            field=models.TextField(default='sin Descripcion'),
            preserve_default=False,
        ),
    ]
