# Generated by Django 3.2.6 on 2023-10-20 14:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0003_auto_20231020_0904'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estadocuenta',
            name='id_paciente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='facturacion.paciente'),
        ),
    ]
